# SPDX-FileCopyrightText: 2025 Yale University
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: eaasi-common
version: 0.1.0
# appVersion: "1.16.0"
description: EAASI Common Helm Chart
type: application
sources:
- https://github.com/eaasi/helm-charts
