# SPDX-FileCopyrightText: 2025 Yale University
# SPDX-License-Identifier: Apache-2.0

# Chart name override
nameOverride: ""

# Full chart name override
fullnameOverride: ""

# Configure the Kubernetes Gateway implementation
gateway:
  # Config the k8s gateway responsible for traffic ingress
  ingress:
    # Override the fullname of the Gateway resource
    fullnameOverride: ""
    # Name of the Gateway resource
    name: ""
    # Name of the GatewayClass resource
    className: ""
    # Annotations for the Gateway resource (optional)
    annotations: {}
    # Labels for the Gateway resource (optional)
    labels: {}
    # Configure the listener(s) for the Gateway
    listeners:
      - name: http
        protocol: HTTP
        port: 80
        # Optional
        hostname: example.com
        allowedRoutes:
          namespaces:
            from: Same
