# SPDX-FileCopyrightText: 2025 Yale University
# SPDX-License-Identifier: Apache-2.0

# Default values for the EAASI Database

operator:
  # -- Should the operator be enabled?
  enabled: false
  # -- Number of replicas
  replicaCount: 1
  # -- Override operator name
  fullnameOverride: cnpg-operator
  # -- Override subchart name
  nameOverride: cloudnative-pg
