# SPDX-FileCopyrightText: 2025 Yale University
# SPDX-License-Identifier: Apache-2.0

# Default values for the EAASI Database

# Configuration for the CNPG operator:
# https://github.com/cloudnative-pg/charts/tree/main/charts/cloudnative-pg
operator:
  # -- Should the operator be enabled?
  enabled: false
  # -- Override operator name
  fullnameOverride: cnpg-operator
  # -- Override subchart name
  # NOTE: The original chart name must be used here for now, because
  #       the upstream chart hard-codes it in multiple templates!
  nameOverride: cloudnative-pg
  # -- Number of replicas
  replicaCount: 1

# Configuration for the CNPG cluster:
# https://github.com/cloudnative-pg/charts/tree/main/charts/cluster
cluster:
  # -- Should the cluster be enabled?
  enabled: true
  # -- Override cluster name
  fullnameOverride: eaasi
  # -- Override subchart name
  nameOverride: database-cluster
  # -- Cluster mode of operation
  mode: standalone
  # -- Type of the CNPG database
  type: postgresql
  # -- Version of the CNPG database
  version:
    postgresql: "17.4"
  # -- CNPG cluster config
  cluster:
    # -- Number of instances
    instances: 1
    # -- Affinity rules for Pods
    affinity:
      enablePodAntiAffinity: true
      podAntiAffinityType: preferred
      topologyKey: kubernetes.io/hostname
    # -- Database storage config
    storage:
      size: 1Gi
