# SPDX-FileCopyrightText: 2025 Yale University
# SPDX-License-Identifier: Apache-2.0

import "../../scripts/config.just"

# Compile chart's configuration files
config-compile-all: \
  (config-compile entrypoint)
