# SPDX-FileCopyrightText: 2025 Yale University
# SPDX-License-Identifier: Apache-2.0

name: setup-helm
description: Helper for installing Helm
runs:
  using: composite
  steps:
    - name: Install Helm
      uses: azure/setup-helm@v4
      with:
        version: v3.17.0
