# SPDX-FileCopyrightText: 2025 Yale University
# SPDX-License-Identifier: Apache-2.0

# Workflow for running various CI checks

name: continuous-integration
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read

jobs:
  checks:
    uses: ./.github/workflows/checks.yaml
    with:
      enable-change-detection: ${{ github.ref != 'refs/heads/main' }}
